- name: enable sudo without tty for some ansible commands
  replace:
    path: /etc/sudoers
    regexp: '^Defaults\s*requiretty'
    replace: 'Defaults  !requiretty'
    backup: yes

- name: enable repos
  copy:
      src: internal.repo
      dest: /etc/yum.repos.d/open_three-tier-app.repo
